apiVersion: v1beta1
kind: AgentConfig
metadata:
  name: {{ cluster-name }}
rendezvousIP: {{ master-0-ip }}
hosts:
  - hostname: master-0
    role: master
    rootDeviceHints:
      deviceName: /dev/sda
    interfaces:
      - name: {{ node-int }}
        macAddress: {{ master-0-mac }}
    networkConfig:
      interfaces:
        - name: {{ node-int }}
          type: ethernet
          state: up
          mac-address: {{ master-0-mac }}
          ipv4:
            enabled: true
            address:
              - ip: {{ master-0-ip }}
                prefix-length: 24
            dhcp: false
          ipv6:
            enabled: false
      dns-resolver:
        config:
          server:
            - {{ dns-ip }}
      routes:
        config:
          - destination: 0.0.0.0/0
            next-hop-address: {{ gwy-ip }}
            next-hop-interface: {{ node-int }}
            table-id: 254
  - hostname: master-1
    role: master
    rootDeviceHints:
      deviceName: /dev/sda
    interfaces:
      - name: {{ node-int }}
        macAddress: {{ master-1-mac }}
    networkConfig:
      interfaces:
        - name: {{ node-int }}
          type: ethernet
          state: up
          mac-address: {{ master-1-mac }}
          ipv4:
            enabled: true
            address:
              - ip: {{ master-1-ip }}
                prefix-length: 24
            dhcp: false
          ipv6:
            enabled: false
      dns-resolver:
        config:
          server:
            - {{ dns-ip }}
      routes:
        config:
          - destination: 0.0.0.0/0
            next-hop-address: {{ gwy-ip }}
            next-hop-interface: {{ node-int }}
            table-id: 254
  - hostname: master-2
    role: master
    rootDeviceHints:
      deviceName: /dev/sda
    interfaces:
      - name: {{ node-int }}
        macAddress: {{ master-2-mac }}
    networkConfig:
      interfaces:
        - name: {{ node-int }}
          type: ethernet
          state: up
          mac-address: {{ master-2-mac }}
          ipv4:
            enabled: true
            address:
              - ip: {{ master-2-ip }}
                prefix-length: 24
            dhcp: false
          ipv6:
            enabled: false
      dns-resolver:
        config:
          server:
            - {{ dns-ip }}
      routes:
        config:
          - destination: 0.0.0.0/0
            next-hop-address: {{ gwy-ip }}
            next-hop-interface: {{ node-int }}
            table-id: 254
  - hostname: worker-0
    role: worker
    rootDeviceHints:
      deviceName: /dev/sda
    interfaces:
      - name: {{ node-int }}
        macAddress: {{ worker-0-mac }}
    networkConfig:
      interfaces:
        - name: {{ node-int }}
          type: ethernet
          state: up
          mac-address: {{ worker-0-mac }}
          ipv4:
            enabled: true
            address:
              - ip: {{ worker-0-ip }}
                prefix-length: 24
            dhcp: false
          ipv6:
            enabled: false
      dns-resolver:
        config:
          server:
            - {{ dns-ip }}
      routes:
        config:
          - destination: 0.0.0.0/0
            next-hop-address: {{ gwy-ip }}
            next-hop-interface: {{ node-int }}
            table-id: 254
  - hostname: worker-1
    role: worker
    rootDeviceHints:
      deviceName: /dev/sda
    interfaces:
      - name: {{ node-int }}
        macAddress: {{ worker-1-mac }}
    networkConfig:
      interfaces:
        - name: {{ node-int }}
          type: ethernet
          state: up
          mac-address: {{ worker-1-mac }}
          ipv4:
            enabled: true
            address:
              - ip: {{ worker-1-ip }}
                prefix-length: 24
            dhcp: false
          ipv6:
            enabled: false
      dns-resolver:
        config:
          server:
            - {{ dns-ip }}
      routes:
        config:
          - destination: 0.0.0.0/0
            next-hop-address: {{ gwy-ip }}
            next-hop-interface: {{ node-int }}
            table-id: 254
  - hostname: worker-2
    role: worker
    rootDeviceHints:
      deviceName: /dev/sda
    interfaces:
      - name: {{ node-int }}
        macAddress: {{ worker-2-mac }}
    networkConfig:
      interfaces:
        - name: {{ node-int }}
          type: ethernet
          state: up
          mac-address: {{ worker-2-mac }}
          ipv4:
            enabled: true
            address:
              - ip: {{ worker-2-ip }}
                prefix-length: 24
            dhcp: false
          ipv6:
            enabled: false
      dns-resolver:
        config:
          server:
            - {{ dns-ip }}
      routes:
        config:
          - destination: 0.0.0.0/0
            next-hop-address: {{ gwy-ip }}
            next-hop-interface: {{ node-int }}
            table-id: 254