apiVersion: nmstate.io/v1
kind: NodeNetworkConfigurationPolicy
metadata:
  annotations:
    description: adding additional single NIC interface with DHCP
  name: ethernet-dhcp
spec:
  desiredState:
    interfaces:
      - ipv4:
          dhcp: true
          enabled: true
        ipv6:
          enabled: false
        name: {{ node-int }}
        state: up
        type: ethernet
  nodeSelector:
    {{ nodeselector-key }}: {{ nodeselector-value }}