apiVersion: v1beta1
kind: AgentConfig
metadata:
  name: {{ cluster-name }}
rendezvousIP: {{ node-ip }}
hosts:
  - hostname: {{ node-hostname }}
    interfaces:
      - name: {{ node-int }}
        macAddress: {{ node-int-mac }}
      - name: {{ node-int2 }}
        macAddress: {{ node-int2-mac }}
    rootDeviceHints:
      deviceName: /dev/sda
    networkConfig:
      interfaces:
        - name: bond0
          type: bond
          state: up
          ipv4:
            enabled: true
            address:
              - ip: {{ node-ip }}
                prefix-length: 24
            dhcp: false
          ipv6:
            enabled: false
          link-aggregation:
            mode: {{ lacp-mode }}
            options:
              miimon: '100'
              lacp_rate: fast
            port:
              - {{ node-int }}
              - {{ node-int2 }}
      dns-resolver:
        config:
          server:
            - {{ dns-ip }}
      routes:
        config:
          - destination: 0.0.0.0/0
            next-hop-address: {{ gwy-ip }}
            next-hop-interface: bond0
            table-id: 254