apiVersion: v1beta1
kind: AgentConfig
metadata:
  name: {{ cluster-name }}
rendezvousIP: {{ node-ip }}
hosts:
  - hostname: {{ node-hostname }}
    interfaces:
      - name: {{ node-int }}
        macAddress: {{ node-int-mac }}
      - name: {{ node-int2 }}
        macAddress: {{ node-int2-mac }}
    rootDeviceHints:
      deviceName: /dev/sda
    networkConfig:
      interfaces:
        - name: {{ node-int }}
          type: ethernet
          state: up
          mac-address: {{ node-int-mac }}
          ipv4:
            enabled: true
            dhcp: true
          ipv6:
            enabled: false
        - name: {{ node-int2 }}
          type: ethernet
          state: up
          mac-address: {{ node-int2-mac }}
          ipv4:
            enabled: true
            dhcp: true
            auto-dns: false
            auto-gateway: false
            auto-routes: false
          ipv6:
            enabled: false